export interface Question {
  id: number
  text: string
  context?: string
  dimension: "economic" | "social"
  weight: number
  reverse?: boolean
  category?: string
}

export const questions: Question[] = [
  // Traditional Economic Questions
  {
    id: 1,
    text: "The government should provide universal healthcare to all citizens.",
    dimension: "economic",
    weight: 1.5,
    reverse: true,
    category: "healthcare",
  },
  {
    id: 2,
    text: "Private companies are generally more efficient than government-run organizations.",
    dimension: "economic",
    weight: 1.2,
    category: "efficiency",
  },
  {
    id: 3,
    text: "Wealthy individuals should pay significantly higher tax rates than middle-class earners.",
    dimension: "economic",
    weight: 1.3,
    reverse: true,
    category: "taxation",
  },
  {
    id: 4,
    text: "Free trade agreements benefit the economy more than they harm it.",
    dimension: "economic",
    weight: 1.1,
    category: "trade",
  },
  {
    id: 5,
    text: "The government should guarantee a job for everyone who wants to work.",
    dimension: "economic",
    weight: 1.4,
    reverse: true,
    category: "employment",
  },
  {
    id: 6,
    text: "Minimum wage laws do more harm than good to the economy.",
    dimension: "economic",
    weight: 1.2,
    category: "labor",
  },
  {
    id: 7,
    text: "Large corporations have too much power and should be broken up.",
    dimension: "economic",
    weight: 1.3,
    reverse: true,
    category: "corporate",
  },
  {
    id: 8,
    text: "The free market, left to its own devices, will solve most economic problems.",
    dimension: "economic",
    weight: 1.5,
    category: "market",
  },
  {
    id: 9,
    text: "Government regulation of business is necessary to protect consumers.",
    dimension: "economic",
    weight: 1.2,
    reverse: true,
    category: "regulation",
  },
  {
    id: 10,
    text: "Private property rights are fundamental to a free society.",
    dimension: "economic",
    weight: 1.4,
    category: "property",
  },

  // Modern Economic Questions
  {
    id: 11,
    text: "Universal Basic Income should be implemented to prepare for mass automation.",
    dimension: "economic",
    weight: 1.4,
    reverse: true,
    category: "automation",
    context: "As AI and robots replace human jobs",
  },
  {
    id: 12,
    text: "Cryptocurrency should replace traditional government-controlled currencies.",
    dimension: "economic",
    weight: 1.2,
    category: "currency",
  },
  {
    id: 13,
    text: "Tech billionaires like Musk and Bezos should be forced to redistribute their wealth.",
    dimension: "economic",
    weight: 1.3,
    reverse: true,
    category: "wealth",
  },
  {
    id: 14,
    text: "AI and automation should be accelerated even if it causes short-term economic disruption.",
    dimension: "economic",
    weight: 1.1,
    category: "accelerationism",
    context: "Accelerationist perspective on technological progress",
  },
  {
    id: 15,
    text: "Worker cooperatives and employee ownership should replace traditional corporations.",
    dimension: "economic",
    weight: 1.3,
    reverse: true,
    category: "cooperative",
  },

  // Traditional Social Questions
  {
    id: 16,
    text: "The government should have the authority to monitor private communications to prevent terrorism.",
    dimension: "social",
    weight: 1.4,
    category: "surveillance",
  },
  {
    id: 17,
    text: "Same-sex couples should have the same marriage rights as heterosexual couples.",
    dimension: "social",
    weight: 1.2,
    reverse: true,
    category: "lgbtq",
  },
  {
    id: 18,
    text: "Traditional family values are essential for a stable society.",
    dimension: "social",
    weight: 1.3,
    category: "family",
  },
  {
    id: 19,
    text: "The death penalty is an appropriate punishment for the most serious crimes.",
    dimension: "social",
    weight: 1.1,
    category: "justice",
  },
  {
    id: 20,
    text: "Drug use should be treated as a health issue rather than a criminal one.",
    dimension: "social",
    weight: 1.2,
    reverse: true,
    category: "drugs",
  },

  // Alt-Right and Nationalist Questions
  {
    id: 21,
    text: "Western civilization is superior to other cultures and should be preserved at all costs.",
    dimension: "social",
    weight: 1.5,
    category: "nationalism",
    context: "Cultural nationalism perspective",
  },
  {
    id: 22,
    text: "Mass immigration is destroying the cultural identity of Western nations.",
    dimension: "social",
    weight: 1.4,
    category: "immigration",
  },
  {
    id: 23,
    text: "Globalism is a conspiracy by elites to undermine national sovereignty.",
    dimension: "social",
    weight: 1.3,
    category: "conspiracy",
  },
  {
    id: 24,
    text: "Men and women have fundamentally different roles that should be maintained by society.",
    dimension: "social",
    weight: 1.2,
    category: "gender",
  },
  {
    id: 25,
    text: "Multiculturalism has failed and ethnic homogeneity creates stronger societies.",
    dimension: "social",
    weight: 1.4,
    category: "ethnicity",
  },

  // Progressive/LGBTQ+ Questions
  {
    id: 26,
    text: "Gender is a social construct and people should be free to identify however they choose.",
    dimension: "social",
    weight: 1.3,
    reverse: true,
    category: "gender-identity",
  },
  {
    id: 27,
    text: "Transgender rights, including access to gender-affirming care, are human rights.",
    dimension: "social",
    weight: 1.4,
    reverse: true,
    category: "transgender",
  },
  {
    id: 28,
    text: "Polyamory and non-traditional relationship structures should be legally recognized.",
    dimension: "social",
    weight: 1.1,
    reverse: true,
    category: "relationships",
  },
  {
    id: 29,
    text: "Children should be taught about diverse sexual orientations and gender identities in school.",
    dimension: "social",
    weight: 1.2,
    reverse: true,
    category: "education",
  },

  // Post-Scarcity/Luxury Space Communism Questions
  {
    id: 30,
    text: "In a post-scarcity society, work should be optional and creative rather than necessary.",
    dimension: "economic",
    weight: 1.3,
    reverse: true,
    category: "post-scarcity",
    context: "Fully Automated Luxury Gay Space Communism perspective",
  },
  {
    id: 31,
    text: "Space exploration and colonization should be humanity's top priority.",
    dimension: "economic",
    weight: 1.1,
    category: "space",
  },
  {
    id: 32,
    text: "Advanced AI should manage resource distribution to eliminate scarcity and inequality.",
    dimension: "economic",
    weight: 1.4,
    reverse: true,
    category: "ai-management",
  },
  {
    id: 33,
    text: "Genetic engineering should be used to eliminate disease and enhance human capabilities.",
    dimension: "social",
    weight: 1.2,
    reverse: true,
    category: "transhumanism",
  },
  {
    id: 34,
    text: "Traditional concepts of nation-states will become obsolete in a space-faring civilization.",
    dimension: "social",
    weight: 1.1,
    reverse: true,
    category: "post-national",
  },

  // Accelerationist Questions
  {
    id: 35,
    text: "Current political and economic systems should be accelerated to their breaking point to create something new.",
    dimension: "economic",
    weight: 1.5,
    category: "accelerationism",
    context: "Accelerationist theory of change through intensification",
  },
  {
    id: 36,
    text: "Technological disruption should be embraced even if it destroys existing social structures.",
    dimension: "social",
    weight: 1.3,
    category: "disruption",
  },
  {
    id: 37,
    text: "Climate change might be solved through radical technological intervention rather than lifestyle changes.",
    dimension: "economic",
    weight: 1.2,
    category: "techno-solutionism",
  },
  {
    id: 38,
    text: "Democracy is too slow and inefficient for the pace of modern technological change.",
    dimension: "social",
    weight: 1.4,
    category: "technocracy",
  },

  // Environmental and Future Questions
  {
    id: 39,
    text: "Eco-fascism may be necessary to prevent environmental collapse.",
    dimension: "social",
    weight: 1.3,
    category: "eco-authoritarianism",
    context: "Authoritarian environmentalism",
  },
  {
    id: 40,
    text: "Individual carbon footprints should be monitored and regulated by the government.",
    dimension: "social",
    weight: 1.2,
    category: "climate-control",
  },
  {
    id: 41,
    text: "Degrowth economics is necessary to prevent environmental catastrophe.",
    dimension: "economic",
    weight: 1.3,
    reverse: true,
    category: "degrowth",
  },
  {
    id: 42,
    text: "Geoengineering projects should be pursued to combat climate change.",
    dimension: "economic",
    weight: 1.1,
    category: "geoengineering",
  },

  // Digital Age Questions
  {
    id: 43,
    text: "Social media companies should be treated as public utilities and regulated accordingly.",
    dimension: "economic",
    weight: 1.2,
    reverse: true,
    category: "tech-regulation",
  },
  {
    id: 44,
    text: "Artificial intelligence development should be slowed down to prevent existential risks.",
    dimension: "social",
    weight: 1.3,
    category: "ai-safety",
  },
  {
    id: 45,
    text: "Virtual reality and digital worlds are as valid as physical reality for human experience.",
    dimension: "social",
    weight: 1.1,
    reverse: true,
    category: "digital-reality",
  },
  {
    id: 46,
    text: "Blockchain technology should replace traditional institutions like banks and governments.",
    dimension: "economic",
    weight: 1.2,
    category: "decentralization",
  },

  // Neo-Reactionary and Dark Enlightenment
  {
    id: 47,
    text: "Democracy has failed and should be replaced with more efficient forms of governance.",
    dimension: "social",
    weight: 1.4,
    category: "anti-democracy",
  },
  {
    id: 48,
    text: "Some groups of people are naturally better suited for leadership than others.",
    dimension: "social",
    weight: 1.5,
    category: "hierarchy",
  },
  {
    id: 49,
    text: "The Enlightenment and its values have led Western civilization astray.",
    dimension: "social",
    weight: 1.3,
    category: "anti-enlightenment",
  },
  {
    id: 50,
    text: "Corporate city-states would be more efficient than traditional democratic governments.",
    dimension: "economic",
    weight: 1.2,
    category: "corporate-governance",
  },

  // Bonus Modern Questions
  {
    id: 51,
    text: "Memes and internet culture are legitimate forms of political expression and organization.",
    dimension: "social",
    weight: 1.0,
    reverse: true,
    category: "meme-politics",
  },
  {
    id: 52,
    text: "Cancel culture is a necessary tool for social justice.",
    dimension: "social",
    weight: 1.3,
    reverse: true,
    category: "cancel-culture",
  },
  {
    id: 53,
    text: "Influencers and content creators should have more political power than traditional politicians.",
    dimension: "social",
    weight: 1.1,
    reverse: true,
    category: "influencer-politics",
  },
  {
    id: 54,
    text: "Psychedelic drugs should be legalized and integrated into mental health treatment.",
    dimension: "social",
    weight: 1.2,
    reverse: true,
    category: "psychedelics",
  },
  {
    id: 55,
    text: "Human consciousness should be uploadable to computers to achieve digital immortality.",
    dimension: "social",
    weight: 1.1,
    reverse: true,
    category: "consciousness-upload",
  },
]
